/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Victor */

#ifndef _Included_Victor
#define _Included_Victor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Victor
 * Method:    allocIndex
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_Victor_allocIndex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     Victor
 * Method:    nativeInsert
 * Signature: (JJ[FI)I
 */
JNIEXPORT jint JNICALL Java_Victor_nativeInsert
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jint);

/*
 * Class:     Victor
 * Method:    nativeDelete
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_Victor_nativeDelete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     Victor
 * Method:    nativeDestroy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Victor_nativeDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
